-- AU Sports Management App - Supabase schema
-- Run this in the Supabase SQL Editor for project: elekmyuctaugbosqpwmj

create table if not exists public."user" (
  id bigint generated by default as identity primary key,
  name varchar,
  email varchar unique,
  rollnumber text,
  mobilenumber bigint,
  password varchar,
  player_level varchar,
  bio text,
  favorite_sport varchar
);

create table if not exists public.room (
  id serial primary key,
  room_name varchar(50),
  room_size integer,
  room_description text,
  is_public boolean default true,
  created_at timestamp without time zone default current_timestamp,
  in_time time without time zone,
  out_time time without time zone,
  sport text,
  rollnumber text default '' not null,
  host_user_id bigint references public."user"(id) on delete set null
);

create table if not exists public.users_in_rooms (
  id serial primary key,
  user_id bigint references public."user"(id) on delete cascade,
  room_id integer references public.room(id) on delete cascade,
  joined_at timestamp without time zone default current_timestamp,
  unique (user_id, room_id)
);

create table if not exists public.announcements (
  id bigserial primary key,
  title text not null,
  description text not null,
  image_url text,
  author_name text,
  created_by bigint references public."user"(id) on delete set null,
  created_at timestamp with time zone default now()
);

-- If tables already exist from an older run, add missing columns safely
alter table public.room add column if not exists host_user_id bigint references public."user"(id) on delete set null;
alter table public.users_in_rooms add column if not exists joined_at timestamp without time zone default current_timestamp;
alter table public."user" add column if not exists player_level varchar;
alter table public."user" add column if not exists bio text;
alter table public."user" add column if not exists favorite_sport varchar;

alter table public."user" enable row level security;
alter table public.room enable row level security;
alter table public.users_in_rooms enable row level security;
alter table public.announcements enable row level security;

drop policy if exists "Allow anon read user" on public."user";
drop policy if exists "Allow anon insert user" on public."user";
drop policy if exists "Allow anon update user" on public."user";
drop policy if exists "Allow anon read room" on public.room;
drop policy if exists "Allow anon insert room" on public.room;
drop policy if exists "Allow anon update room" on public.room;
drop policy if exists "Allow anon read users_in_rooms" on public.users_in_rooms;
drop policy if exists "Allow anon insert users_in_rooms" on public.users_in_rooms;
drop policy if exists "Allow anon delete users_in_rooms" on public.users_in_rooms;
drop policy if exists "Allow anon read announcements" on public.announcements;
drop policy if exists "Allow anon insert announcements" on public.announcements;

create policy "Allow anon read user" on public."user" for select to anon using (true);
create policy "Allow anon insert user" on public."user" for insert to anon with check (true);
create policy "Allow anon update user" on public."user" for update to anon using (true);

create policy "Allow anon read room" on public.room for select to anon using (true);
create policy "Allow anon insert room" on public.room for insert to anon with check (true);
create policy "Allow anon update room" on public.room for update to anon using (true);

create policy "Allow anon read users_in_rooms" on public.users_in_rooms for select to anon using (true);
create policy "Allow anon insert users_in_rooms" on public.users_in_rooms for insert to anon with check (true);
create policy "Allow anon delete users_in_rooms" on public.users_in_rooms for delete to anon using (true);

create policy "Allow anon read announcements" on public.announcements for select to anon using (true);
create policy "Allow anon insert announcements" on public.announcements for insert to anon with check (true);

grant usage on schema public to anon, authenticated, service_role;
grant all on all tables in schema public to anon, authenticated, service_role;
grant all on all sequences in schema public to anon, authenticated, service_role;
